server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.179.70:3306/navigation_system?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "@oPHc701eA0dcQEATe2Ae"

    druid:
      # 基础配置
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 3000

      # 连接保活
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 3600000
      keep-alive: true
      validation-query: SELECT 1
      test-while-idle: true

      # 监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*



  mail:
    protocol: smtp # 邮件协议
    host: smtp.163.com #网易邮箱 smtp 服务器地址
    port: 465
    username: 18794295151@163.com  #发件人邮箱地址
    password: YJaPC9HSPpNh3mVF #授权码
    default-encoding: UTF-8 #编码字符集
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true     #  启用 SSL
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true               # 开启日志调试，建议上线关闭


    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    redis:
      host: 47.96.179.70 # 更换成自己的 Redis 地址
      port: 8109
      password: ~gmb7GK%aviH!518aU%8
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms


http:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
#logging:
#  level:
#    com.navigation: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
logging:
  level:
    org.springframework: INFO
  pattern:
    dateformat: HH:mm:ss:SSS

  jmx:
    enabled: true



mybatis:
  #mapper配置文
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.navigation.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 唐十八陵导览系统接口文档
    description: " 唐十八陵导览系统接口文档"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          com.navigation.controller


deepseek:
  api-key: sk-47437c1d15e84a02b1521d6bd7d0658b
  api-url: https://api.deepseek.com/v1/chat/completions
  timeout: 10000

  # langchain4j:
  #   open-ai:
  #     chat-model:
  #       base-url: https://dashscope.aliyuncs.com/compatible-mod
  #       api-key: sk-6c02451e08ce4700a7baf803e92ecb13
  #       model-name: qwen-plus
  #       log-requests: true
  #       log-responses: true
  #     streaming-chat-model: #流式输出
  #       base-url: https://dashscope.aliyuncs.com/compatible-mod
  #       api-key: sk-6c02451e08ce4700a7baf803e92ecb13
  #       model-name: qwen-plus
  #       log-requests: true
  #       log-responses: true
  #     embedding-model: #配置向量模型
  #       base-url: https://dashscope.aliyuncs.com/compatible-mod
  #       api-key: sk-6c02451e08ce4700a7baf803e92ecb13
  #       model-name: text-embedding-v3
  #       log-requests: true
  #       log-responses: true
  #       max-segments-per-batch: 10

  #community: #配置向量数据库连接信息
   # redis:
    #  host: 47.96.179.70
     # port: 6380
